package com.kmbl.OrderManagementService.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "customer")
public class Customer implements User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String customerId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String address;

    @DynamoDBAttribute
    private List<String> orderHistory;

    @DynamoDBIgnore
    public UserType getUserType() {
        return UserType.CUSTOMER;
    }

    @Override
    public String getName() {
        return name;
    }

    @DynamoDBIgnore
    public void addToOrderHistory(String orderId) {
        orderHistory.add(orderId);
    }
}
