package com.kmbl.OrderManagementService.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "order_items")
public class OrderItem {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String orderItemId;

    @DynamoDBAttribute
    private String productId;
    @DynamoDBAttribute
    private String quantity;
    @DynamoDBAttribute
    private OrderStatus status;
    @DynamoDBAttribute
    private String sellerId;
    @DynamoDBAttribute
    private Date createdAt;
    @DynamoDBAttribute
    private Date updatedAt;

}
