package com.kmbl.OrderManagementService.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "order_items")
public class OrderItem {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String orderItemId;

    @DynamoDBAttribute
    private String productId;

    @DynamoDBAttribute
    private String quantity;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private OrderStatus status;

    @DynamoDBAttribute
    private String sellerId;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute
    private Date createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute
    private Date updatedAt;
}
