package com.kmbl.OrderManagementService.models;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@NoArgsConstructor
@AllArgsConstructor
@Data
@DynamoDBTable(tableName = "orders")
public class Order {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String orderId;

    @DynamoDBAttribute
    private String customerId;

    @DynamoDBAttribute
    private String deliveryAddress;

    @DynamoDBAttribute
    private List<OrderItem> orderItems;
}
